// auto generated by go tool dist

package sys

const DefaultGoroot = `/Users/aram/go`
const TheVersion = `devel +dc2a518 Thu Apr 21 18:10:59 2016 +0200`
const Goexperiment = ``
const StackGuardMultiplier = 1
